import { ApiProperty } from '@nestjs/swagger';

export class CreateMediaDto {
  @ApiProperty({ description: 'Original name of the file' })
  originalName: string;

  @ApiProperty({ description: 'Filename generated by the server' })
  filename: string;

  @ApiProperty({ description: 'Original URL of the file' })
  originalUrl: string;

  @ApiProperty({ description: 'Path to the file' })
  path: string;


  @ApiProperty({ description: 'Nounu ID' })
  userId?: string;

  @ApiProperty({ description: 'Nounu ID' })
  JobId?: string;

  @ApiProperty({ description: 'Type of media (e.g. image, video, document)' })
  typeMedia: string;

  // ... other properties like description, alt text, etc.
}
